name: Backend Docker Build

on:
  push:
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to local registry (اگر auth داری)
      - name: Login to Local Registry
        uses: docker/login-action@v3
        with:
          registry: 185.8.174.197:5000
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and Push to both registries
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./apps/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/mkdir98/mercur-backend:latest
            185.8.174.197:5000/mercur-backend:latest